//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRPORT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirportDBEntities1 : DbContext
    {
        public AirportDBEntities1()
            : base("name=AirportDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static AirportDBEntities1 _context;

        public static AirportDBEntities1 GetContext()
        {
            if (_context == null)
                _context = new AirportDBEntities1();
            return _context;

        }

        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ArrivalAirPort> ArrivalAirPort { get; set; }
        public virtual DbSet<Commander> Commander { get; set; }
        public virtual DbSet<DepartureAirPort> DepartureAirPort { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<Passenger> Passenger { get; set; }
        public virtual DbSet<Plane> Plane { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
    }
}
