//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRPORT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int RouteID { get; set; }
        public int DepAirPortID { get; set; }
        public int ArrAirPortID { get; set; }
        public Nullable<decimal> TicketCost { get; set; }
        public Nullable<System.TimeSpan> FlightDuration { get; set; }
        public string Name { get; set; }
    
        public virtual ArrivalAirPort ArrivalAirPort { get; set; }
        public virtual DepartureAirPort DepartureAirPort { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
