//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRPORT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int IDPassenger { get; set; }
        public int IDFlight { get; set; }
        public string TicketNumber { get; set; }
        public int TicketID { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
